### ISSUE TITLE
Names of Arabic counters do not match Unicode/CLDR naming

### ISSUE THREAD

**Issue by behnam** [w3c/predefined-counter-styles#1]
The numeral set called `persian` in the document is called as "EXTENDED ARABIC-INDIC" in Unicode standard, to be used in Persian, Urdu, and many other Asian languages/locales.

The letter set called `persian-alphabetic` looks good.

Finally, Abjad Numerals need better research before put here, as there are two main version of it: Easter (mostly used in North-East Africa, Saudi Arabia and West Asia) and Western (a.k.a. Maghrebi, mostly used in North-West Africa). And, of course, the character set for Persian/Urdu edition of the Eastern version would be different from the Arabic-language one.

See https://en.wikipedia.org/wiki/Abjad_numerals for some basic info, but we need better resources to move forward.

**Comment by r12a** [comment]
@behnam, thanks for the comments
-  the naming of the `persian` counter-style dates from a long while back and has been adopted by browsers (see [the test results](https://www.w3.org/International/tests/repo/results/custom-counter-styles#arabic)) as a name for a standardised approach, and i don't think we can easily change that now.  Of course, using the new CSS properties one can name these sequences however one wants in one's CSS.
- If you have more information about the abjad styles, please let us know and we can add them to the document.  We may need to check whether people actually use, or want to use, those for counter styles though.

**Comment by r12a** [comment]
Closing this for now, but if you have a proposal for the abjad counter styles, feel free to reopen.

**Comment by r12a** [comment]
The comment about abjad counters is picked up again in https://github.com/w3c/predefined-counter-styles/issues/13
