### ISSUE TITLE
Persian Alphabetic and Persian Abjad also used for Arabic

### ISSUE THREAD

**Issue by ironymark** [w3c/predefined-counter-styles#13]
See https://www.w3.org/TR/predefined-counter-styles/#persian-abjad. We also need arabic-abjad and arabic-alphabetic. These lettered styles are used for numbering in books in Arabic and part of the Office document standard. It should be separate Arabic versions of these as Arabic Unicode is different to Persian Unicode (e.g. Persian uses: ک while Arabic uses: ك).

**Comment by r12a** [comment]
@ironymark thanks for the information that those counter styles are in use, that's helpful.  Can you point to or provide authoritative information about the algorithms for those styles?

**Comment by ironymark** [comment]
Sure. I have two…
1. https://en.wikipedia.org/wiki/Abjad_numerals
2. "Office Open XML Part 1 - Fundamentals And Markup Language Reference" page 1572 http://www.ecma-international.org/publications/standards/Ecma-376.htm

**Comment by r12a** [comment]
@ironymark after some research and analysis, i added an arabic-abjad style (and also a maghrebi-abjad style suggested by @ntounsi).  See http://w3c.github.io/predefined-counter-styles/#arabic-styles

The [Wikipedia article](https://en.wikipedia.org/wiki/Abjad_numerals) wasn't terribly clear about what is what, and which constitute counter-styles as opposed to alphabetic orderings.  (Note that i also added a comparison table at the bottom of the section linked to above.)

The WP article was also unclear about the system to use. There are comparisons with the Hebrew style (which is additive) and mentions of numbers in the 100s, but it wasn't clear which sequences  that is relevant to.  I added the arabic-abjad style as fixed, like the others.

I'm going to close this issue for now, but please reopen it if you want to provide additional information.
