### ISSUE TITLE
The "Maghrebian Abjad" sequence

### ISSUE THREAD

**Issue by ntounsi** [w3c/predefined-counter-styles#14]
In addition to the two lists  of Arabic letters in CSS counter styles, "persian-alphabetic" (aka Hijā’ī) and "persian-abjad" (aka Abjadī),  I think there is another list (or version) of Arabic Abjadī. The "Maghrebian Abjad" sequence. It is a little bit different from the well known one, the "Persian Abjad" (or "Arabic Abjad")

 Persian-abjad :    أبجد هوز حطي كلمن سعفص قرشت ثخذ ضظغ  
Magrebian-abjad :  أبجد هوز حطي كلمن صعفض قرست ثخذ ظغش 

(See also picture attached)

The Magrebian-abjad is what I learned at school as a second sequence beside the more scholar sequence which is called alphabetic (and is also the Unicode sequence).
I think the Magrebian-abjad is easier to pronounce, especially at the end. 
" ... thakhudh ẓughshin " vs " ... thakhudh ḍuẓghin "

So here is my suggestion:

@counter-style maghrebian-abjad {
system: fixed;
suffix: ') '; 
symbols: 
  '\627' '\628' '\62C' '\62F' '\647\200D' '\648' '\632' '\62D' '\637' '\64A' '\6A9' '\644' '\645' '\646' 
 '\635' '\639' '\641' '\636' '\642' '\631' '\633' '\62A' '\62B' '\62E' '\630' '\638' '\63A' '\634';
/* symbols: 
'ا' 'ب' 'ج' 'د' 'ه‍' 'و' 'ز' 'ح' 'ط' 'ي' 'ک' 'ل' 'م' 'ن' 
 'ص'  'ع' 'ف' 'ض'
'ق' 'ر'  'س'  'ت'  'ث' 'خ' 'ذ' 'ظ' 'غ' 'ش'
  */;
} 

Note that I put 
ARABIC LETTER YEH (U+064A)
instead of
ARABIC LETTER FARSI YEH (U+06CC)

Best regards,

Najib

![maghrebian-persian-abjad](https://cloud.githubusercontent.com/assets/15004708/20885606/b3be3742-bae9-11e6-8643-55c82bdf195f.png)

**Comment by ntounsi** [comment]
About implementation, only Mozilla based UAs are OK. Here is an example.
http://196.200.140.8/Tests/maghrebianAbjadCounterStyle.html

- The fifth item in the list, letter Heh ('\647\200D'), should have initial form because of the ZWJ :-(
- The suffix I chose is ). It is mirrored in rtl context

**Comment by r12a** [comment]
@ntounsi I added this in https://github.com/w3c/predefined-counter-styles/commit/5fa09901f2e9c561bf03a11a24d45299d895f606

See https://w3c.github.io/predefined-counter-styles/#arabic-styles

Najib, i think there is one small error in your code above. You use keheh ک instead of kaf ك.  Since i'm pretty sure that's an error, and since it is the only difference from the maghrebi sequence described in Wikipedia, i used kaf.

Please reopen this issue if you want to come back on that.

**Comment by ntounsi** [comment]
You're right. My error. It's Kaf  '\643' instead of Keheh '\6A9' .
 
```
@counter-style maghrebian-abjad {
system: fixed;
suffix: ') '; 
symbols: 
  '\627' '\628' '\62C' '\62F' '\647\200D' '\648' '\632' '\62D' '\637' '\6CC' '\643' '\644' '\645' '\646' '\635' '\639' '\641' '\636'
  '\642' '\631' '\633' '\62A' '\62B' '\62E' '\630' '\638' '\63A' '\634';
/* symbols: 
'ا' 'ب' 'ج' 'د' 'ه‍' 'و' 'ز' 'ح' 'ط' 'ی' 'ك' 'ل' 'م' 'ن'  'ص'  'ع' 'ف' 'ض'
'ق' 'ر'  'س'  'ت'  'ث' 'خ' 'ذ' 'ظ' 'غ' 'ش'
  */;
} 
```
