### ISSUE TITLE
New counting style proposal: Ideographic counting mark

### ISSUE THREAD

**Issue by c933103** [w3c/predefined-counter-styles#19]
copy from https://github.com/w3c/csswg-drafts/issues/2097
Note that relevant characters still have not been encoded into Unicode yet. See https://blogs.adobe.com/CCJKType/2016/01/ideographic-tally-marks.html
```
@counter-style cjk-tally-mark{
  system: additive;
  additive-symbols: 5 "\1D376", 4 "\1D375", 3 "\1D374", 2 "\1D373", 1 "\1D372";
  /* Relevant chracters still in proposal status in Unicode, see https://blogs.adobe.com/CCJKType/2016/01/ideographic-tally-marks.html */
  suffix: " ";
}
````

**Comment by r12a** [comment]
Added for review to the ED at http://w3c.github.io/predefined-counter-styles/#cjk-tally-mark

How should i list your name in the acknowledgements section?

**Comment by faceless2** [comment]
The Unicode document referenced by Ken Lunde's blog above is http://www.unicode.org/L2/L2015/15328-tally-marks.pdf - it refers to four tally styles:

* tally
* box tally
* ideographic tally
* dot-dash tally

"cjk-tally-mark" covers the third, and I don't think that "box tally" and "dot-dash tally" have been encoded in Unicode (yet?). But the first has - for consistency shouldn't it be added as well? It would be

```css
@counter-style tally-mark {
  system: additive;
  additive-symbols: 5 '\1D378', 1 '\1D377'; /* symbols: 5 𝍸, 1 𝍷; */
  suffix: " ";
}
```

(reference: see https://www.unicode.org/L2/L2016/16065-tally-marks.pdf)

**Comment by r12a** [comment]
Since we focus on international writing systems, tally-mark seemed a little borderline for this doc, but i have now added it at https://github.com/w3c/predefined-counter-styles/pull/29

Thanks.
