### ISSUE TITLE
New style proposal: A variation of cjk-numeral with different separator

### ISSUE THREAD

**Issue by c933103** [w3c/predefined-counter-styles#22]
The default style for cjk-numeral used a symbol as separator that Korean would not use in regular horizontal writing, according to post #4 in https://github.com/w3c/klreq/issues/22
Note: sometimes in Chinese these other separators may also be used, according to my udnerstanding
Note 2: I am not too sure about how frequently used in different languages are these ideographic numbers counters without place value word

**Comment by r12a** [comment]
Fixed for Korean by https://github.com/w3c/predefined-counter-styles/pull/42

Pending further clarity for the Chinese case, closing this.

**Comment by c933103** [comment]
> Fixed for Korean by https://github.com/w3c/predefined-counter-styles/pull/42
> 
> Pending further clarity for the Chinese case, closing this.

I mean, in Chinese people would also use like "甲. XXX" other than "甲、XXX"
