### ISSUE TITLE
Wrong Editor ID in ReSpec config

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/predefined-counter-styles#24]
Just noticed some copy/pasta in the Editor's list... it's using my id "39125". So in /TR/ it looks like I edited this document 🥳

**Comment by r12a** [comment]
hi @marcoscaceres.  Thanks for that. I changed it in the editor's version.  I'm wondering whether there's a need to change it in the WG Note before we make more substantive changes (since i guess you'd need to be looking at the code to see it, and make an effort to track down the number)?

**Comment by marcoscaceres** [comment]
No sure how it works once it hits TR (or how TR picks up the data), but I guess it would need to be republished or updated.

**Comment by r12a** [comment]
This is now fixed. Closing.
