### ISSUE TITLE
Should we add more Latin counter styles?

### ISSUE THREAD

**Issue by r12a** [w3c/predefined-counter-styles#3]
one of our WG members ran a tool against the CLDR database recently to convert alphabetic lists to the new CSS custom counter style rules.  For example, the tool came up with the following for Swedish:

/\* sv _/
@counter-style swedish {
    system: alphabetic;
    symbols: '\61' '\62' '\63' '\64' '\65' '\66' '\67' '\68' '\69' '\6a' '\6b' '\6c' '\6d' '\6e' '\6f' '\70' '\71' '\72' '\73' '\74' '\75' '\76' '\77' '\78' '\79' '\7a' '\e5' '\e4' '\f6' ;
    /_ symbols: ‭'a' ‭'b' ‭'c' ‭'d' ‭'e' ‭'f' ‭'g' ‭'h' ‭'i' ‭'j' ‭'k' ‭'l' ‭'m' ‭'n' ‭'o' ‭'p' ‭'q' ‭'r' ‭'s' ‭'t' ‭'u' ‭'v' ‭'w' ‭'x' ‭'y' ‭'z' ‭'å' ‭'ä' ‭'ö' */
}

If you use this for counters on a list, say, when you got to the 26th item in the list you'd see

z. blah blah blah
å. now a 27th item
ä. and one for the 28th
ö. and the last letter of the alphabet
aa. and so on
ab. and so on....

So i have a number of questions (using a hypothetical slovak list numbering style):

a. do people who write in Swedish or other languages number lists using the extra letters of the alphabet? ie. å, ä, ö

ä. are the alphabetic lists in CLDR a good source of information for compiling such lists (i'm expecting the answer to be 'it depends on the language')?

b. if the answer to (a) is yes, are there people receiving this message who can vouch for the sequences that would be needed?

c. should we add a whole bunch of Latin custom templates to the document [Custom Counter Styles](http://w3c.github.io/predefined-counter-styles/)?

č. there isn't really a (č), i just wanted to use the c hacek ;)

**Comment by henke37** [comment]
I'm Swedish and I can't say I've ever needed a this long list. But I can say that MS Excel does not use ÅÄÖ for the column labels. On the same topic, apparently Swedish collators sort w and v equally. Not sure if you should skip w for lists indexes then.

**Comment by prlbr** [comment]
I’m German. German uses the Latin alphabet plus the additional letters _ä_, _ö_, _ü_ and _ß_. But I’ve never seen a list using these additional letters as list counters in practice.

The only thing that I can think of are glossaries and indexes in a book. Those are often sorted and you might find the additional letters in there (though _ä_ is often sorted as _ae_ or  _a_; _ö_ as _oe_ or _o_; _ü_ as _ue_ or _u_; _ß_ is never found at the beginning of a word but is almost always treated as _ss_, if the correct letter is not available). But when you subdivide a glossary/index into parts corresponding to initial letters, you would use explicit headings and not automatic counters, I think.

**Comment by r12a** [comment]
thanks @henke37 and @prlbr. You are the only people who have responded, so it's looking like this is not leading to a requirement.

**Comment by Crissov** [comment]
Instead of alphabetic styles with more letters, I think it may make sense to add a counter style with _less_. I know I’ve seen lists that omitted `j` (or `i`), but I’m not sure they would also combine `u`, `v` and `w` into a single marker (or two). `lower-alpha-ancient` perhaps?

I’m currently researching the use of (lowercase) broken letters / blackletter as list markers. They used to be somewhat common among German mathematicians and engineers for deeply nested hierarchies where roman numbers, decimal numbers, roman letters and greek letters had already been used. (Alphabetic lists inside German Fraktur / Sütterlin texts often employed Antiqua letters with closing parentheses or period as a suffix.)

**Comment by asmusf** [comment]
Fraktur typesetting had precise rules when to use antiqua. It was their version of italics. Foreign words, for example, were set in Antiqua. While I'm familiar with the use of Fraktur for mathematical variables, I can't recall any instance where it might have been used in counter.

Not having both 'i' and 'j' in a list is something that I've seen quite often, not limited to ancient texts, but driven by the desire not to have two easily confused labels. 'u' and 'v' are pretty far down (which limits the source for potential examples to very long lists). For old lists that use the pure Latin alphabet, 'w' would not exist.

Whether Swedish lists do (or used to) conflate 'v' and 'w' (not 'u' and 'w') in list counters is something I don't know. In general, the sorting order has to explicitly account for everything in the core alphabet, but counter styles have no such requirement.

There are quite a few languages that use the Latin script and some use a very limited number of the letters 'a-z'. The latter would be the most intriguing cases, but languages for which just a few of the Latin letters are not used natively are more common.

**Comment by r12a** [comment]
Given no further movement on this issue, i'm closing it.  Can be reopened if needed, or new issues can be raised to propose specific European styles.
