### ISSUE TITLE
Is haleme a typo?

### ISSUE THREAD

**Issue by nt1m** [w3c/predefined-counter-styles#55]
There are a few counter styles with "haleme" in the name. Is it supposed to be "halehame" ?

**Comment by nt1m** [comment]
Also is `ethiopic-halehame-ti-et` lacking a suffix descriptor?

I've noticed a few other differences from WebKit which implements an older version of the styles: https://github.com/WebKit/WebKit/pull/13323/files

**Comment by r12a** [comment]
Thanks for the report. FIxed.
