### ISSUE TITLE
Should `upper-serbo-croatian` and `lower-serbo-croatian` be renamed?

### ISSUE THREAD

**Issue by dbaron** [w3c/predefined-counter-styles#58]
In https://github.com/w3c/csswg-drafts/issues/8636#issuecomment-1591665495 @jensimmons mentioned that she heard feedback that [`lower-serbo-croatian`](https://w3c.github.io/predefined-counter-styles/#lower-serbo-croatian) and [`upper-serbo-croatian`](https://w3c.github.io/predefined-counter-styles/#upper-serbo-croatian) should be renamed, perhaps to `upper-serbian` and `lower-serbian`, given the current local use of language names.  (I'm not sure what issues are involved here, and to what extent those issues do or don't involve the implications of whether a particular language name suggests use of a Cyrillic or Latin alphabet.)  It's possible that @jensimmons could add more details.

**Comment by jensimmons** [comment]
Yes, we opened this PR: https://github.com/w3c/predefined-counter-styles/pull/57

**Comment by dbaron** [comment]
Oops, I searched open issues but not PRs!

**Comment by r12a** [comment]
Thanks @dbaron.  Closing this in favour of https://github.com/w3c/predefined-counter-styles/pull/57
