### ISSUE TITLE
Emoji decimal styles

### ISSUE THREAD

**Issue by Crissov** [w3c/predefined-counter-styles#7]
Unicode has defined emoji characters for numbers 0 through 10 with a key-cap appearance. They could be used as either fixed or numeric custom counter styles:
- `emoji-numbers` fixed: 1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣🔟
- `emoji-decimal` numeric: 0️⃣1️⃣2️⃣3️⃣4️⃣5️⃣6️⃣7️⃣8️⃣9️⃣

Since the latter is just international digits followed by U+FE0F ‘Variation Selector-16’ and U+20E3 ‘Combining Enclosing Keycap’, I wonder if `suffix: "\FE0F\20E3"` would suffice, but I suppose that would only work for single-digit numbers if at all.

PS: These are used already in chat, instant messaging and micro-blogging, e.g. on [Twitter](https://twitter.com/FIFAWWC/status/746251804246171648).

**Comment by r12a** [comment]
See https://github.com/w3c/predefined-counter-styles/issues/9
