### ISSUE TITLE
Astronomic and astrologic (symbolic/emoji) styles

### ISSUE THREAD

**Issue by Crissov** [w3c/predefined-counter-styles#8]
There are some sequences of symbols from astrology that have a clearly defined order and could thus be used as custom counter styles in certain scenarios. 

For some, it’s okay to repeat in cycles:
- `zodiac-signs` U+2648…53 ♈♉♊♋♌♍♎♏♐♑♒♓ (without ophicus ⛎ U+26CE), possibly with Emoji variation selector ♈️♉️♊️♋️♌️♍️♎️♏️♐️♑️♒️♓️
  - beginning around Northward equinox: ♈♉♊♋♌♍♎♏♐♑♒♓
  - beginning around Northern solstice: ♋♌♍♎♏♐♑♒♓♈♉♊
  - beginning around Southward equinox: ♎♏♐♑♒♓♈♉♊♋♌♍
  - beginning around Southern solstice: ♑♒♓♈♉♊♋♌♍♎♏♐ ≈ `month-symbols`
- `week-day-symbols` (see [Wikipedia](https://en.wikipedia.org/wiki/Names_of_the_days_of_the_week#Days_named_after_planets), alternative characters for Sun and Moon available)
  - Sunday–Saturday, 0…6:  ☼☾♂☿♃♀♄
  - Monday–Sunday, 1…7:  ☾♂☿♃♀♄☼

Others are fixed and limited to ten markers at most:
- `planets`: 1…8 ☿♀♁♂♃♄♅♆ U+263F … U+2646 (astrologic alternative symbol for Uranus available at U+26E2)
- `solar-system`: 0…9 ☼☿♀♁♂♃♄♅♆♇ U+263C Sun + `planets` + U+2647 Pluto

**Comment by r12a** [comment]
See my comments in the two following issues you raised.
