### ISSUE TITLE
Clock face emoji counter style

### ISSUE THREAD

**Issue by Crissov** [w3c/predefined-counter-styles#9]
At U+1F550…B, there are twelve emoji characters showing the face of an analog clock, i.e. the full hours. That could be used as a cyclic custom counter in one of two ways:
- `clock-face` 1…12: 🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚🕛
- `clock-face` 0…11: 🕛🕐🕑🕒🕓🕔🕕🕖🕗🕘🕙🕚

Half-hours, but not quarter-hours or other parts, are also available at the succeeding twelve code positions U+1F55C…67, but I’m not convinced they’d be useful in a counter style:
- 🕜🕝🕞🕟🕠🕡🕢🕣🕤🕥🕦🕧

**Comment by r12a** [comment]
I agree. Note that this document is intended to provide styles that international users are likely to commonly need.

**Comment by Crissov** [comment]
I understand that the primary motivation for publishing this document is i18n, hence the WG in charge. I’m quite okay with it preferably listing _existing_ usage. 

I object, though, to the notion implied by closing #7, #8, #9 and #10 collectively that this draft shall never introduce “creative” counter styles that have no or little attested usage, because (from the intro) …

> […] you can use the styles here for inspiration, or adapt them to suit your preferences.

I’ve seen manual use of emoji keycap digits (#7) for short lists in instant messages and, I think, on Twitter, too. Neither CCS nor CSS:CS3 includes an example that showcases a variation selector or a combining character, so that or the enclosing forms in #10 could be useful on technical grounds alone.

For what it’s worth, I‘ve opened a new [public collection of custom counter styles](https://github.com/Crissov/css-counters).

**Comment by r12a** [comment]
Reopening this to remind me to include a link in the document to the collection.

**Comment by r12a** [comment]
Done here https://github.com/w3c/predefined-counter-styles/commit/ce33a894be673029046ae517d7997ab97798e7b0
